apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-homelab-cluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Project for k8s homelab - K8S clusters appsets
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-homelab-clusters-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Project for k8s homelab - K8S clusters configuration secrets
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'