apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-secrets-plugin
  namespace: argocd
data:
  baseUrl: http://argocd-secrets-plugin.argocd.svc.cluster.local:8080
  requestTimeout: '60'
  token: $argocd-secrets-plugin:plugin.argocd-secrets-plugin.token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-secrets-plugin
  namespace: argocd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-secrets-plugin
  namespace: argocd
  labels:
    app: argocd-secrets-plugin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-secrets-plugin
  template:
    metadata:
      labels:
        app: argocd-secrets-plugin
    spec:
      serviceAccountName: argocd-secrets-plugin
      serviceAccount: argocd-secrets-plugin
      containers:
      - name: argocd-secrets-plugin
        image: quay.io/vadimzharov/argocd-secrets-plugin:test-release
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: ARGOCD_PLUGIN_TOKEN
            valueFrom:
              secretKeyRef:
                name: argocd-secrets-plugin
                key: plugin.argocd-secrets-plugin.token
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-secrets-plugin
  namespace: argocd
spec:
  selector:
    app: argocd-secrets-plugin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-secrets-plugin
  namespace: argocd
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-secrets-plugin
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: argocd-secrets-plugin
    namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-secrets-plugin
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-secrets-plugin
  namespace: ingress-nginx
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-secrets-plugin
  namespace: ingress-nginx
subjects:
  - kind: ServiceAccount
    name: argocd-secrets-plugin
    namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-secrets-plugin
