apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus
  namespace: prometheus
  annotations:
    k8s-dashboard-group: Monitoring
    k8s-dashboard-appname: Prometheus
spec:
  parentRefs:
    - name: cilium-gw
      namespace: cilium-system
      sectionName: https-gw
  hostnames:
    - "prometheus.{{ domainname }}"
  rules:
    - backendRefs:
        - name: prometheus-server
          port: 9090
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus-write
  namespace: prometheus
spec:
  parentRefs:
    - name: cilium-gw
      namespace: cilium-system
      sectionName: https-gw
  hostnames:
    - "prometheus-write.{{ domainname }}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /api/v1/write
      backendRefs:
        - name: prometheus-server
          port: 9090
