apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hass
  namespace: argocd
  annotations:
    appset-dashboard-appname: "Home Assistant"
    appset-dashboard-groupname: "Home automation"
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  hass: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{name}}-hass'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: hass
          values: |      
            service:
              main:
                primary: true
                enabled: true
                controller: main                
                ports:
                  http:
                    port: 8123
            route:
              main:
                enabled: true
                kind: HTTPRoute
                labels:
                  k8s-dashboard-group: Smart-home
                  k8s-dashboard-appname: HomeAssistant                  
                parentRefs:
                  - name: cilium-gw
                    namespace: cilium-system
                hostnames:
                  - hass.{{ domainname }}
                rules:  
                - matches:
                  - path:
                      type: PathPrefix
                      value: /
                  backendRefs:
                  - name: hass
                    port: 8123                    
            # ingress:
            #   main:
            #     enabled: true
            #     className: nginx
            #     hosts:
            #       - host: hass.{{ domainname }}
            #         paths:
            #           - path: /
            #             pathType: Prefix
            #             service:
            #               name: hass
            #               port: 8123
            persistence:
              config:
                enabled: true
                type: emptyDir
                globalMounts: 
                  - path: /config/
            secrets:
              b-r-secret:
                enabled: true
                labels: {}
                annotations: {}
                stringData:
                  AWS_BUCKET: {{ awsbucket }}
                  AWS_KEY: {{ awskey }}
                  AWS_SECRET_KEY: {{ awssecretkey }}
                  ENCRYPT_PASSWORD: {{ encryptpassword }}
              pdbackup-secret:
                enabled: true
                labels: {}
                annotations: {}
                stringData:
                  PDBACKUP_S3_BUCKET: {{ awsbucket }}
                  PDBACKUP_S3_ACCESS_KEY: {{ awskey }}
                  PDBACKUP_S3_SECRET_KEY: {{ awssecretkey }}
                  PDBACKUP_KOPIA_PASSWORD: {{ encryptpassword }}                      
            configMaps:
              b-r-settings:
                enabled: true
                data:
                  S3_BUCKET_FOLDER: "homehass"
                  S3_FILE_PREFIX: "hass-backup"
                  DIR_TO_BACKUP: "/config"
                  DIR_TO_RESTORE: "/config"  
                  BACKUP_INTERVAL: "24h"
                  PRUNE_INTERVAL: "48h"
                  COPIES_TO_KEEP: "35"
                  FORCE_RESTORE: "True"
              pdbackup-settings:
                enabled: true
                data:
                  PDBACKUP_S3_PREFIX: "hass-pbbackup"
                  PDBACKUP_SOURCE_DIR: "/config"
                  PDBACKUP_TARGET_DIR: "/config"  
                  PDBACKUP_BACKUP_INTERVAL: "24h"
                  PDBACKUP_HOSTNAME: "hass"
                  PDBACKUP_RETENTION_KEEP_LATEST: "35"
                  PDBACKUP_FORCE_RESTORE: "true"
            controllers:
              main:
                type: deployment
                enabled: true
                initContainers:
                  hass-restore:
                    image: 
                      repository: ghcr.io/vadimzharov/pdbackup
                      pullPolicy: IfNotPresent
                      tag: 0.0.3
                    args:
                      - restore
                    envFrom:
                    - secretRef:
                        name: hass-pdbackup-secret
                    - configMapRef:
                        name: hass-pdbackup-settings
                containers:
                  main:
                    image:
                      repository: docker.io/homeassistant/home-assistant
                      pullPolicy: IfNotPresent
                      tag: 2022.2.0
                    env:
                      TZ: UTC
                  hass-backup-daemon:
                    image: 
                      repository: ghcr.io/vadimzharov/pdbackup
                      pullPolicy: IfNotPresent
                      tag: 0.0.3
                    args:
                      - daemon
                    envFrom:
                    - secretRef:
                        name: hass-pdbackup-secret
                    - configMapRef:
                        name: hass-pdbackup-settings
        repoURL: https://bjw-s-labs.github.io/helm-charts
        chart: app-template
        targetRevision: 3.4.0
      destination:
        server: '{{server}}' 
        namespace: hass
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      