apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: immich-m
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
        - clusters:
            selector:
              matchLabels:
                immich-m: "installed"
                csi-nfs: "installed"
        - plugin:
            configMapRef:
              name: argocd-secrets-plugin
            input:
              parameters:
                secretName: "immich-app-secrets"
  template:
    metadata:
      name: '{{name}}-immich-m'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: immich-m-data
          values: |
            controllers: 
              main:
               enabled: false
            rawResources:
              immich-data:
                apiVersion: v1
                kind: PersistentVolumeClaim
                forceRename: "immich-m-data"
                spec:
                  spec:
                    storageClassName: sc-nfs-default
                    accessModes:
                      - ReadWriteMany
                    resources:
                      requests:
                        storage: 10Gi
        repoURL: https://bjw-s-labs.github.io/helm-charts
        chart: app-template
        targetRevision: 4.4.0
      - helm:
          releaseName: immich-m
          values: |
            server:
              controllers:
                main:
                  containers:
                    main:
                      image:
                        repository: ghcr.io/immich-app/immich-server
                        pullPolicy: IfNotPresent
                        tag: v2.3.1
                      env:
                        DB_HOSTNAME:
                          valueFrom:
                            secretKeyRef:
                              name: immich-database-restored-app
                              key: host
                        DB_USERNAME:
                          valueFrom:
                            secretKeyRef:
                              name: immich-database-restored-app
                              key: user
                        DB_PASSWORD:
                          valueFrom:
                            secretKeyRef:
                              name: immich-database-restored-app
                              key: password
                        DB_DATABASE_NAME:
                          valueFrom:
                            secretKeyRef:
                              name: immich-database-restored-app
                              key: dbname
              route:
                main:
                  enabled: true
                  kind: HTTPRoute
                  labels:
                    k8s-dashboard-group: Photos
                    k8s-dashboard-appname: Immich-M
                  parentRefs:
                    - name: cilium-gw
                      namespace: cilium-system
                  hostnames:
                    - immich-m.{{ domainname }}
                  rules:  
                  - matches:
                    - path:
                        type: PathPrefix
                        value: /
                    backendRefs:
                    - name: immich-m-server
                      port: 2283               
            valkey:
              enabled: true

            immich:
              persistence:
                library:
                  existingClaim: immich-m-data
        repoURL: https://immich-app.github.io/immich-charts
        chart: immich
        targetRevision: 0.10.3
      destination:
        server: '{{server}}' 
        namespace: immich-m
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      