apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openwebui
  namespace: argocd
  annotations:
    appset-dashboard-appname: "OpenWebUI"
    appset-dashboard-groupname: "AI tools"
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  openwebui: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{name}}-openwebui'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: openwebui
          values: |
            ollama:              
              enabled: false
            persistence:
              enabled: false
              storageClass: ""
            route:
              enabled: true
              extraLabels:
                k8s-dashboard-group: AI tools
                k8s-dashboard-appname: OpenWebUI
              hostnames: 
                - chat.{{ domainname }}
              parentRefs:
                - name: cilium-gw
                  namespace: cilium-system
                  sectionName: https-gw
            #extraEnvVars:
            #- name: OPENAI_API_KEY
            #  value: "{{ openaiapikey }}"
            #- name: OAUTH_CLIENT_ID
            #  value: "{{ authowebuiclientid }}"
            #- name: OAUTH_CLIENT_SECRET
            #  value: "{{ authowebuiclientsecret }}"
            #- name: OAUTH_PROVIDER_NAME
            #  value: "authentik"
            #- name: OPENID_PROVIDER_URL
            #  value: "https://auth.{{ domainname }}/application/o/openwebui/.well-known/openid-configuration"
            #- name: OPENID_REDIRECT_URI
            #  value: "https://chat.{{ domainname }}/oauth/oidc/callback"
            #- name: ENABLE_OAUTH_SIGNUP
            #  value: "true"
        repoURL: https://helm.openwebui.com/
        chart: open-webui
        targetRevision: 15.2.0
      destination:
        server: '{{server}}' 
        namespace: openwebui
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      