apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: radarr
  namespace: argocd
  annotations:
    appset-dashboard-appname: "Radarr media server"
    appset-dashboard-groupname: "Media"
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  radarr: "installed"
                  csi-nfs: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{name}}-radarr'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: radarr
          values: |
            controllers:            
              main:
                type: deployment
                initContainers:
                  radarr-restore-config:
                    image: 
                      repository: ghcr.io/vadimzharov/pdbackup
                      pullPolicy: IfNotPresent
                      tag: 0.0.8
                    args: 
                      - restore
                    envFrom:
                    - secretRef:
                       name: radarr-pdbackup-secret
                    - configMapRef:
                       name: radarr-pdbackup-settings             
                containers:
                  main:
                    image: 
                      repository: lscr.io/linuxserver/radarr
                      pullPolicy: IfNotPresent
                      tag: latest
                  radarr-backup-config-daemon:
                    image: 
                      repository: ghcr.io/vadimzharov/pdbackup
                      pullPolicy: IfNotPresent
                      tag: 0.0.8
                    args:
                      - daemon
                    envFrom:
                    - secretRef:
                       name: radarr-pdbackup-secret
                    - configMapRef:
                       name: radarr-pdbackup-settings                    
            service:
              main:
                primary: true
                enabled: true
                controller: main
                ports:
                  http:
                    port: 7878
            route:
              main:
                enabled: true
                kind: HTTPRoute
                labels:
                  k8s-dashboard-group: Media
                  k8s-dashboard-appname: Radarr
                parentRefs:
                  - name: cilium-gw
                    namespace: cilium-system
                hostnames:
                  - radarr.{{ domainname }}
                rules:  
                - matches:
                  - path:
                      type: PathPrefix
                      value: /
                  backendRefs:
                  - name: radarr
                    port: 7878
            persistence:
              config:
                enabled: true
                type: emptyDir
                globalMounts:
                  - path: /config
                    readOnly: false
              root-folder:
                enabled: true
                type: persistentVolumeClaim
                existingClaim: radarr-radarr-pvc                
                globalMounts:
                  - path: /radarr
                    readOnly: false
              tranarr:
                enabled: true
                type: persistentVolumeClaim
                existingClaim: radarr-tranarr-pvc
                globalMounts:
                  - path: /tranarr
                    readOnly: false                    
            configMaps:
              pdbackup-settings:
                enabled: true
                data:
                  PDBACKUP_S3_BUCKET: "k8s-apps-pdbackup"                
                  PDBACKUP_S3_PREFIX: "radarr-pbbackup"
                  PDBACKUP_SOURCE_DIR: "/config"
                  PDBACKUP_TARGET_DIR: "/config"  
                  PDBACKUP_BACKUP_INTERVAL: "1h"
                  PDBACKUP_HOSTNAME: "radarr"
                  PDBACKUP_RETENTION_KEEP_LATEST: "10"
                  PDBACKUP_FORCE_RESTORE: "true"
            secrets:
              pdbackup-secret:
                enabled: true
                labels: {}
                annotations: {}
                stringData:
                  PDBACKUP_S3_ENDPOINT: "http://{{ minioendpoint }}"
                  PDBACKUP_S3_ACCESS_KEY: {{ miniokey }}
                  PDBACKUP_S3_SECRET_KEY: {{ miniosecretkey }}
                  PDBACKUP_KOPIA_PASSWORD: {{ encryptpassword }}
            rawResources:
              tranarr-pv:
                apiVersion: v1
                kind: PersistentVolume
                spec:
                  spec:
                    capacity:
                      storage: 10Gi
                    accessModes:
                      - ReadWriteMany
                    persistentVolumeReclaimPolicy: Retain
                    storageClassName: sc-nfs-default
                    csi:
                      driver: nfs.csi.k8s.io
                      readOnly: false
                      # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
                      # make sure this value is unique for every share in the cluster
                      volumeHandle: "nfs-server#radarr-tranarr#radarr-app"
                      volumeAttributes:
                        server: {{ k8s-nfs-server-name }}
                        share: {{ k8s-tranarr-share }}
              tranarr-pvc:
                apiVersion: v1
                kind: PersistentVolumeClaim
                spec:
                  spec:
                    storageClassName: sc-nfs-default
                    accessModes:
                      - ReadWriteMany
                    resources:
                      requests:
                        storage: 10Gi
                    volumeName: radarr-tranarr-pv
              radarr-pv:
                apiVersion: v1
                kind: PersistentVolume
                spec:
                  spec:
                    capacity:
                      storage: 10Gi
                    accessModes:
                      - ReadWriteMany
                    persistentVolumeReclaimPolicy: Retain
                    storageClassName: sc-nfs-default
                    csi:
                      driver: nfs.csi.k8s.io
                      readOnly: false
                      # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
                      # make sure this value is unique for every share in the cluster
                      volumeHandle: "nfs-server#radarr#radarr-app"
                      volumeAttributes:
                        #server: {{ k8s-nfs-server-name }}
                        #share: {{ k8s-radarr-share }}
                        server: {{ truenas-nfs-ip }}
                        share: "{{ truenas-arr-share }}/arr/media/movies"                        
              radarr-pvc:
                apiVersion: v1
                kind: PersistentVolumeClaim
                spec:
                  spec:
                    storageClassName: sc-nfs-default
                    accessModes:
                      - ReadWriteMany
                    resources:
                      requests:
                        storage: 10Gi
                    volumeName: radarr-radarr-pv                    
        repoURL: https://bjw-s-labs.github.io/helm-charts
        chart: app-template
        targetRevision: 3.4.0
      destination:
        server: '{{server}}' 
        namespace: radarr
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      
