apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trilium
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  trilium: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{name}}-trilium'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: trilium
          values: |      
            service:
              main:
                primary: true
                enabled: true
                controller: main                
                ports:
                  http:
                    port: 8080
            ingress:
              main:
                enabled: true
                className: nginx
                hosts:
                  - host: trilium-new.{{ domainname }}
                    paths:
                      - path: /
                        pathType: Prefix
                        service:
                          name: trilium
                          port: 8080
            persistence:
              config:
                enabled: true
                type: emptyDir
                globalMounts: 
                  - path: /home/node/trilium-data
            secrets:
              b-r-secret:
                enabled: true
                labels: {}
                annotations: {}
                stringData:
                  AWS_BUCKET: {{ awsbucket }}
                  AWS_KEY: {{ awskey }}
                  AWS_SECRET_KEY: {{ awssecretkey }}
                  ENCRYPT_PASSWORD: {{ encryptpassword }}
            configMaps:
              b-r-settings:
                enabled: true
                data:
                  S3_BUCKET_FOLDER: "trilium"
                  S3_FILE_PREFIX: "trilium-backup"
                  DIR_TO_BACKUP: "/home/node/trilium-data"
                  DIR_TO_RESTORE: "/home/node/trilium-data"
                  BACKUP_INTERVAL: "1h"
                  PRUNE_INTERVAL: "48h"
                  COPIES_TO_KEEP: "35"
                  FORCE_RESTORE: "True"   
            controllers:
              main:
                type: deployment
                enabled: true
                initContainers:
                  trilium-restore:
                    image: 
                      repository: quay.io/vadimzharov/podbackup
                      pullPolicy: IfNotPresent
                      tag: latest
                    command:
                      - podbackup
                    args:
                      - restore
                    envFrom:
                    - secretRef:
                        name: trilium-b-r-secret
                    - configMapRef:
                        name: trilium-b-r-settings
                containers:
                  main:
                    image:
                      repository: docker.io/trilium/server
                      pullPolicy: IfNotPresent
                      tag: :latest
                    env:
                      TRILIUM_PORT: "8080"
                  #trilium-backup-daemon:
                  #  image: 
                  #    repository: quay.io/vadimzharov/podbackup
                  #    pullPolicy: IfNotPresent
                  #    tag: latest
                  #  command:
                  #    - podbackup
                  #  args:
                  #    - backup-daemon
                  #  envFrom:
                  #  - secretRef:
                  #      name: trilium-b-r-secret
                  #  - configMapRef:
                  #      name: trilium-b-r-settings
        repoURL: https://bjw-s.github.io/helm-charts
        chart: app-template
        targetRevision: 3.4.0
      destination:
        server: '{{server}}' 
        namespace: trilium
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      