apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    appset-dashboard-appname: "Prometheus"
    appset-dashboard-groupname: "Monitoring"
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  prometheus: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{name}}-prometheus'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: prometheus
          values: |
            server:
              retention: "14d"
              retentionSize: "50GB"
              extraFlags:
                - storage.tsdb.wal-compression
                - enable-feature=remote-write-receiver
              resources:
                requests:
                  cpu: 250m
                  memory: 512Mi
                limits:
                  cpu: "1"
                  memory: 2Gi
              persistentVolume:
                enabled: true
                size: 50Gi
                storageClass: "synas-csi-retain"
              route:
                enabled: true
                annotations:
                  k8s-dashboard-group: Monitoring
                  k8s-dashboard-appname: Prometheus
                hostnames:
                  - prometheus.{{ domainname }}
                parentRefs:
                  - name: cilium-gw
                    namespace: cilium-system
                    sectionName: https-gw
              additionalRouteRules:
                - matches:
                    - path:
                        type: PathPrefix
                        value: /api/v1/write
                  hostname: prometheus-write.{{ domainname }}
                  parentRefs:
                    - name: cilium-gw
                      namespace: cilium-system
                      sectionName: https-gw
            alertmanager:
              enabled: false
            prometheus-pushgateway:
              enabled: false
        repoURL: https://prometheus-community.github.io/helm-charts
        chart: prometheus
        targetRevision: 26.0.0
      destination:
        server: '{{server}}'
        namespace: prometheus
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
