apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: obsidian
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  obsidian: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{name}}-obsidian'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: obsidian
          values: |      
            service:
              main:
                primary: true
                enabled: true
                controller: main                
                ports:
                  http:
                    port: 3000
            route:
              main:
                enabled: true
                kind: HTTPRoute
                parentRefs:
                  - name: cilium-gw
                    namespace: cilium-system
                hostnames:
                  - obsidian.{{ domainname }}
                rules:  
                - matches:
                  - path:
                      type: PathPrefix
                      value: /
                  backendRefs:
                  - name: obsidian
                    port: 3000
            controllers:
              main:
                type: deployment
                enabled: true
                containers:
                  main:
                    image:
                      repository: ghcr.io/linuxserver/obsidian
                      pullPolicy: IfNotPresent
                      tag: latest
        repoURL: https://bjw-s-labs.github.io/helm-charts
        chart: app-template
        targetRevision: 4.6.2
      destination:
        server: '{{server}}' 
        namespace: obsidian
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      