apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: openwebui
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  openwebui: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{name}}-openwebui'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: openwebui
          values: |
            ollama:              
              enabled: false
            ingress:
              enabled: true
              class: nginx
              host: chat.{{ domainname }}
              tls: true
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: "0.6.9"
              pullPolicy: "IfNotPresent"
            extraEnvVars:
            - name: OPENAI_API_KEY
              value: "{{ openaiapikey }}"
        repoURL: https://helm.openwebui.com/
        chart: open-webui
        targetRevision: 6.13.0
      destination:
        server: '{{server}}' 
        namespace: openwebui
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      