apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  vaultwarden: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{name}}-vaultwarden'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: vaultwarden
          values: |      
            service:
              main:
                primary: true
                enabled: true
                controller: main
                ports:
                  http:
                    port: 80
              websocket:
                primary: true
                enabled: true
                controller: main
                ports:
                  port-ws:
                    port: 3012
            ingress:
              main:
                enabled: true
                className: nginx
                hosts:
                  - host: vaultwarden.{{ domainname }}
                    paths:
                      - path: /
                        pathType: Prefix
                        service:
                          name: vaultwarden
                          port: 80
            persistence:
              config:
                enabled: true
                type: emptyDir
                globalMounts: 
                  - path: /data
            secrets:
              b-r-secret:
                enabled: true
                labels: {}
                annotations: {}
                stringData:
                  AWS_BUCKET: {{ awsbucket }}
                  AWS_KEY: {{ awskey }}
                  AWS_SECRET_KEY: {{ awssecretkey }}
                  ENCRYPT_PASSWORD: {{ encryptpassword }}
            configMaps:
              b-r-settings:
                enabled: true
                data:
                  S3_BUCKET_FOLDER: "vaultwarden-backup"
                  S3_FILE_PREFIX: "vw-backup"
                  DIR_TO_BACKUP: "/data"
                  DIR_TO_RESTORE: "/data"  
                  BACKUP_INTERVAL: "2h"
                  PRUNE_INTERVAL: "24h"
                  COPIES_TO_KEEP: "35"
                  FORCE_RESTORE: "True"    
            controllers:
              main:
                type: deployment
                enabled: true
                initContainers:
                  vaultwarden-restore:
                    image: 
                      repository: quay.io/vadimzharov/podbackup
                      pullPolicy: IfNotPresent
                      tag: latest
                    command:
                      - podbackup
                    args:
                      - restore
                    envFrom:
                    - secretRef:
                        name: vaultwarden-b-r-secret
                    - configMapRef:
                        name: vaultwarden-b-r-settings
                containers:
                  main:
                    image:
                      repository: docker.io/vaultwarden/server
                      pullPolicy: IfNotPresent
                      tag: latest
                    env:
                      LOG_LEVEL: info 
                      WEBSOCKET_ENABLED: 'true'
                      SIGNUPS_ALLOWED: 'false'
                      ADMIN_TOKEN: {{ vwadminkey }}
                  #vaultwarden-backup-daemon:
                  #  image: 
                  #    repository: quay.io/vadimzharov/podbackup
                  #    pullPolicy: IfNotPresent
                  #    tag: latest
                  #  command:
                  #    - podbackup
                  #  args:
                  #    - backup-daemon
                  #  envFrom:
                  #  - secretRef:
                  #      name: vaultwarden-b-r-secret
                  #  - configMapRef:
                  #      name: vaultwarden-b-r-settings
        repoURL: https://bjw-s.github.io/helm-charts
        chart: app-template
        targetRevision: 3.4.0
      destination:
        server: '{{server}}' 
        namespace: vaultwarden
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      