apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vllm-qwen2-5-7b-instruct
  namespace: argocd
  annotations:
    appset-dashboard-appname: "vllm Qwen2.5-7B-Instruct model"
    appset-dashboard-groupname: "AI tools"
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  vllm: "vllm-qwen2-5-7b-instruct"
                  nvidia-gpu: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{name}}-vllm'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: vllm
          values: |
            servingEngineSpec:
              strategy:
                type: Recreate            
              modelSpec:
                - name: qwen
                  enabled: true
                  repository: vllm/vllm-openai
                  tag: "v0.25.1"
                  modelURL: "Qwen/Qwen2.5-7B-Instruct"
                  hf_token: "{{ vllm-hf-token }}"
                  enableTool: true
                  toolCallParser: "hermes"

                  replicaCount: 1

                  requestCPU: 4
                  requestMemory: "16Gi"
                  requestGPU: 1

                  limitCPU: 4
                  limitMemory: "20Gi"

                  vllmConfig:
                    dtype: bfloat16
                    maxModelLen: 32768
                    tensorParallelSize: 1
                    gpuMemoryUtilization: 0.90
                    enablePrefixCaching: true

                  lmcacheConfig:
                    enabled: false

                  keda:
                    enabled: false

              vllmApiKey: "{{ vllm-master-key }}"

              containerPort: 8000
              servicePort: 8000

            sharedPvcStorage:
              enabled: true
              size: "60Gi"
              accessModes:
                - ReadWriteOnce
            routerSpec:
              enableRouter: false           
        repoURL: https://vllm-project.github.io/production-stack
        chart: vllm-stack
        targetRevision: 0.1.12
      destination:
        server: '{{server}}' 
        namespace: vllm
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      