apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jellyfin
  namespace: argocd
  annotations:
    appset-dashboard-appname: "Jellyfin media server"
    appset-dashboard-groupname: "Media"
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  jellyfin: "installed"
                  csi-nfs: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{name}}-jellyfin'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: jellyfin
          values: |
            service:
              main:
                controller: main
                ports:
                  http:
                    port: 8096
            ingress:
              main:
                enabled: true
                annotations:
                  k8s-dashboard-group: Media
                  k8s-dashboard-appname: Jellyfin
                className: nginx
                hosts:
                  - host: jellyfin.{{ domainname }}
                    paths:
                      - path: /
                        pathType: Prefix
                        service:
                          name: jellyfin
                          port: 8096
                  - host: jelarr.{{ domainname }}
                    paths:
                      - path: /
                        pathType: Prefix
                        service:
                          name: jellyfin
                          port: 8096                             
            persistence:
              config:
                enabled: true
                type: emptyDir
                globalMounts: 
                  - path: /jellyfin-data
              gpu-card:
                enabled: true
                type: hostPath
                hostPath: /dev/dri/renderD128
                globalMounts: 
                  - path: /dev/dri/renderD128
              arr:
                enabled: true
                type: persistentVolumeClaim
                existingClaim: jellyfin-arr-pvc
                globalMounts: 
                  - path: /arr
              dedicated-movies:
                enabled: true
                type: persistentVolumeClaim
                existingClaim: jellyfin-dedicated-movies-pvc
                globalMounts: 
                  - path: /dedicated-movies/
              arr-d:
                enabled: true
                type: persistentVolumeClaim
                existingClaim: jellyfin-arr-d-pvc
                globalMounts: 
                  - path: /arr-d-movies/
              youtube:
                enabled: true
                type: persistentVolumeClaim
                existingClaim: jellyfin-youtube-pvc
                globalMounts: 
                  - path: /youtube/
            secrets:
              b-r-secret:
                enabled: true
                labels: {}
                annotations: {}
                stringData:
                  S3_ENDPOINT: {{ minioendpoint }}
                  AWS_KEY: {{ miniokey }}
                  AWS_SECRET_KEY: {{ miniosecretkey }}
              pdbackup-secret:
                enabled: true
                labels: {}
                annotations: {}
                stringData:
                  PDBACKUP_S3_ENDPOINT: "http://{{ minioendpoint }}"
                  PDBACKUP_S3_ACCESS_KEY: {{ miniokey }}
                  PDBACKUP_S3_SECRET_KEY: {{ miniosecretkey }}
                  PDBACKUP_KOPIA_PASSWORD: {{ encryptpassword }}
            configMaps:
              b-r-settings:
                enabled: true
                data:
                  AWS_BUCKET: "arr-bkp"
                  S3_BUCKET_FOLDER: "jelarr-config"
                  S3_FILE_PREFIX: "jelarr-config"
                  BACKUP_INTERVAL: "1h"
                  PRUNE_INTERVAL: "48h"
                  COPIES_TO_KEEP: "35"
                  FORCE_RESTORE: "true"
                  DIR_TO_BACKUP: /jellyfin-data
                  DIR_TO_RESTORE: /jellyfin-data
                  ARCHIVE_TYPE: targz
              pdbackup-settings:
                enabled: true
                data:
                  PDBACKUP_S3_BUCKET: "k8s-apps-pdbackup"                
                  PDBACKUP_S3_PREFIX: "jellyfin-pbbackup"
                  PDBACKUP_SOURCE_DIR: "/jellyfin-data"
                  PDBACKUP_TARGET_DIR: "/jellyfin-data"  
                  PDBACKUP_BACKUP_INTERVAL: "1h"
                  PDBACKUP_HOSTNAME: "jellyfin"
                  PDBACKUP_RETENTION_KEEP_LATEST: "5"
                  PDBACKUP_FORCE_RESTORE: "true"
            controllers:
              main:
                initContainers:
                  jellyfin-restore:
                    image: 
                      repository: ghcr.io/vadimzharov/pdbackup
                      pullPolicy: IfNotPresent
                      tag: 0.0.3
                    #command:
                    #  - podbackup
                    args:
                      - restore
                    envFrom:
                    - secretRef:
                       name: jellyfin-pdbackup-secret
                    - configMapRef:
                       name: jellyfin-pdbackup-settings                    
                    # - secretRef:
                    #     name: jellyfin-b-r-secret
                    # - configMapRef:
                    #     name: jellyfin-b-r-settings
                containers:
                  main:
                    image:
                      repository: docker.io/jellyfin/jellyfin
                      pullPolicy: IfNotPresent
                      tag: latest
                    env:
                      JELLYFIN_DATA_DIR: "/jellyfin-data"
                      JELLYFIN_CONFIG_DIR: "/jellyfin-data/config"
                      TZ: "CST"
                      MALLOC_TRIM_THRESHOLD_: "131072"
                    resources:
                      limits:
                        gpu.intel.com/i915: 1
                  jellyfin-backup-daemon:
                    image: 
                      repository: ghcr.io/vadimzharov/pdbackup
                      pullPolicy: IfNotPresent
                      tag: 0.0.3
                    #command:
                    #  - podbackup
                    args:
                      - daemon
                    envFrom:
                    - secretRef:
                       name: jellyfin-pdbackup-secret
                    - configMapRef:
                       name: jellyfin-pdbackup-settings
                    #- secretRef:
                    #    name: jellyfin-b-r-secret
                    #- configMapRef:
                    #    name: jellyfin-b-r-settings
            rawResources:
              arr-pv:
                apiVersion: v1
                kind: PersistentVolume
                spec:
                  spec:
                    capacity:
                      storage: 10Gi
                    accessModes:
                      - ReadWriteMany
                    persistentVolumeReclaimPolicy: Retain
                    storageClassName: sc-nfs-default
                    csi:
                      driver: nfs.csi.k8s.io
                      readOnly: false
                      # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
                      # make sure this value is unique for every share in the cluster
                      volumeHandle: "nfs-server#k8s-jellyfin#k8s-arr-share"
                      volumeAttributes:
                        server: {{ k8s-nfs-server-name }}
                        share: {{ k8s-arr-share }}
              arr-pvc:
                apiVersion: v1
                kind: PersistentVolumeClaim
                spec:
                  spec:
                    storageClassName: sc-nfs-default
                    accessModes:
                      - ReadWriteMany
                    resources:
                      requests:
                        storage: 10Gi
                    volumeName: jellyfin-arr-pv
              dedicated-movies-pv:
                apiVersion: v1
                kind: PersistentVolume
                spec:
                  spec:
                    capacity:
                      storage: 10Gi
                    accessModes:
                      - ReadWriteMany
                    persistentVolumeReclaimPolicy: Retain
                    storageClassName: sc-nfs-default
                    csi:
                      driver: nfs.csi.k8s.io
                      readOnly: false
                      # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
                      # make sure this value is unique for every share in the cluster
                      volumeHandle: "nfs-server#k8s-jellyfin#k8s-dedicated-share"
                      volumeAttributes:
#                        server: {{ k8s-nfs-server-name }}
#                        share: {{ k8s-tranarr-dedicated-share }}
                        server: {{ truenas-nfs-ip }}
                        share: "{{ truenas-arr-share }}/dedicated-movies"                        
              dedicated-movies-pvc:
                apiVersion: v1
                kind: PersistentVolumeClaim
                spec:
                  spec:
                    storageClassName: sc-nfs-default
                    accessModes:
                      - ReadWriteMany
                    resources:
                      requests:
                        storage: 10Gi
                    volumeName: jellyfin-dedicated-movies-pv
              arr-d-pv:
                apiVersion: v1
                kind: PersistentVolume
                spec:
                  spec:
                    capacity:
                      storage: 10Gi
                    accessModes:
                      - ReadWriteMany
                    persistentVolumeReclaimPolicy: Retain
                    storageClassName: sc-nfs-default
                    csi:
                      driver: nfs.csi.k8s.io
                      readOnly: false
                      # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
                      # make sure this value is unique for every share in the cluster
                      volumeHandle: "nfs-server#k8s-jellyfin#k8s-arr-d-share"
                      volumeAttributes:
                        server: {{ k8s-nfs-server-name }}
                        share: {{ k8s-arr-d-share }}
              arr-d-pvc:
                apiVersion: v1
                kind: PersistentVolumeClaim
                spec:
                  spec:
                    storageClassName: sc-nfs-default
                    accessModes:
                      - ReadWriteMany
                    resources:
                      requests:
                        storage: 10Gi
                    volumeName: jellyfin-arr-d-pv
              youtube-pv:
                apiVersion: v1
                kind: PersistentVolume
                spec:
                  spec:
                    capacity:
                      storage: 10Gi
                    accessModes:
                      - ReadWriteMany
                    persistentVolumeReclaimPolicy: Retain
                    storageClassName: sc-nfs-default
                    csi:
                      driver: nfs.csi.k8s.io
                      readOnly: false
                      # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
                      # make sure this value is unique for every share in the cluster
                      volumeHandle: "nfs-server#k8s-jellyfin#k8s-youtube-share"
                      volumeAttributes:
                        server: {{ k8s-nfs-server-name }}
                        share: {{ k8s-youtube-share }}
              youtube-pvc:
                apiVersion: v1
                kind: PersistentVolumeClaim
                spec:
                  spec:
                    storageClassName: sc-nfs-default
                    accessModes:
                      - ReadWriteMany
                    resources:
                      requests:
                        storage: 10Gi
                    volumeName: jellyfin-youtube-pv                    
        repoURL: https://bjw-s-labs.github.io/helm-charts
        chart: app-template
        targetRevision: 3.4.0
      destination:
        server: '{{server}}' 
        namespace: jellyfin
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      
