apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloudnative-pg
  namespace: argocd
  annotations:
    appset-dashboard-appname: "CloudNativePG operator"
    appset-dashboard-groupname: "K8S tools"  
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  cloudnative-pg: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{name}}-cloudnative-pg'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: cloudnative-pg
        repoURL: https://cloudnative-pg.github.io/charts
        chart: cloudnative-pg
        targetRevision: 0.27.0
      - repoURL: https://github.com/cloudnative-pg/plugin-barman-cloud.git
        targetRevision: 'v0.9.0'
        path: kubernetes/    
      destination:
        server: '{{server}}' 
        namespace: cnpg-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
      