apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: headlamp
  namespace: argocd  
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  headlamp: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{name}}-headlamp'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: headlamp
          values: |
            config:
              oidc:
                clientID: "kubernetes-api"
                clientSecret: "{{ kubeapiclientsecret }}"
                issuerURL: "https://pocket-id.{{ domainname }}"
                scopes: "email,profile"
            ingress:
              enabled: true
              ingressClassName: "nginx"
              hosts:
                - host: console-{{ name }}.{{ domainname }}
                  paths:
                  - path: /
                    type: ImplementationSpecific
        repoURL: https://kubernetes-sigs.github.io/headlamp/
        chart: headlamp
        targetRevision: 0.38.0
      destination:
        server: '{{server}}' 
        namespace: headlamp
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      