apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: harbor-new
  namespace: argocd
  annotations:
    ai-agent-inventory-appname: "Harbor (Registry)"
    appset-dashboard-appname: "Harbor registry"
    appset-dashboard-groupname: "K8S tools"
    k8s-dashboard-group: "Tools"
    k8s-dashboard-appname: "Harbor registry"              
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  harbor-new: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"  
  template:
    metadata:
      name: '{{name}}-harbor-new'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: harbor
          values: |
            expose:
              type: route
              route:
                labels: 
                  k8s-dashboard-group: Devops-tools
                  k8s-dashboard-appname: Harbor
                annotations: {}
                # References to the parent gateways
                parentRefs: 
                  - name: '{{ metadata.labels.harbor-route-gw }}'
                    namespace: cilium-system
                    sectionName: https-gw
                    group: gateway.networking.k8s.io
                    kind: Gateway
                  - name: '{{ metadata.labels.harbor-route-gw }}'
                    namespace: cilium-system
                    sectionName: https-gw-5k
                    group: gateway.networking.k8s.io
                    kind: Gateway                    
                hosts: 
                  - harbor.{{ domainname }}
              tls:
                enabled: true
                certSource: none
              ingress:
                hosts:
                  core: harbor.{{ domainname }}
                className: '{{ metadata.labels.harbor-ingress }}'
            externalURL: https://harbor.{{ domainname }}:5000
            logLevel: info
            #persistence:
            #  enabled: true
            #  resourcePolicy: "keep"
            #  persistentVolumeClaim:
            #    registry:
            #      existingClaim: ""
            database:
              type: external
              external:
                host: "harbor-database-restored-rw"
                port: "5432"
                username: "harbor"
                password: "{{ harborpgpassword }}"
                coreDatabase: "app"                
        repoURL: https://helm.goharbor.io
        chart: harbor
        targetRevision: 1.18.1
      - helm:
          releaseName: harbor-db-data
          values: |
            controllers: 
              main:
               enabled: false
            secrets:
              harbor-db-credentials:
                enabled: true
                stringData:
                  username: {{ harborpgusername }}
                  password: {{ harborpgpassword }}
                type: kubernetes.io/basic-auth
            rawResources:
              minio-credentials:
                apiVersion: v1
                kind: Secret
                forceRename: "minio-credentials"
                spec:
                  stringData:
                    accesskey: {{ miniokey }}
                    secretkey: {{ miniosecretkey }}
              harbor-db-creds:
                apiVersion: v1
                kind: Secret
                forceRename: "harbor-db-user"
                spec:
                  stringData:
                    username: {{ harborpgusername }}
                    password: {{ harborpgpassword }}
              backupobjectstore:
                apiVersion: barmancloud.cnpg.io/v1
                kind: ObjectStore
                forceRename: "harbor-registry-db-backup"
                spec:
                  spec:
                    retentionPolicy: "5d"
                    configuration:
                      destinationPath: s3://cloudnative-pg-backups/harbor-registry-db
                      endpointURL: http://{{ minioendpoint }}
                      s3Credentials:
                        accessKeyId:
                          name:  minio-credentials
                          key: accesskey
                        secretAccessKey:
                          name: minio-credentials
                          key: secretkey
                      wal:
                        compression: gzip
              scheduledbackup:
                apiVersion: postgresql.cnpg.io/v1
                kind: ScheduledBackup
                forceRename: harbor-db-backup
                spec:
                  spec:
                    schedule: "0 0 * * * *" 
                    backupOwnerReference: self
                    cluster:
                      name: harbor-database-restored
                    method: plugin
                    pluginConfiguration:
                      name: barman-cloud.cloudnative-pg.io                        
              pgsqlcluster:
                apiVersion: postgresql.cnpg.io/v1
                kind: Cluster
                forceRename: "harbor-database-restored"
                annotations:
                  cnpg.io/skipEmptyWalArchiveCheck: "enabled"
                spec:
                  spec:
                    instances: 1

                    storage:
                      size: 2Gi
                      storageClass: synas-csi-delete

                    bootstrap:
                      recovery:
                        source: origin
                        owner: harbor
                        secret:
                          name: harbor-db-user

                    externalClusters:
                      - name: origin
                        plugin:
                          name: barman-cloud.cloudnative-pg.io
                          parameters:
                            barmanObjectName: harbor-registry-db-backup
                            serverName: harbor-database-restored
                    imageName: ghcr.io/cloudnative-pg/postgresql:16.2-3
                    plugins:
                    - name: barman-cloud.cloudnative-pg.io
                      isWALArchiver: true
                      parameters:
                        barmanObjectName: harbor-registry-db-backup
        repoURL: https://bjw-s-labs.github.io/helm-charts
        chart: app-template
        targetRevision: 4.4.0
      destination:
        server: '{{server}}' 
        namespace: harbor
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      