apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nvidia-gpu
  namespace: argocd
  annotations:
    appset-dashboard-appname: "NVIDIA GPU Operator"
    appset-dashboard-groupname: "K8S tools"  
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  nvidia-gpu: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{name}}-nvidia-gpu'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: nvidia-gpu
          values: |
            driver:
              enabed: false
        repoURL: https://helm.ngc.nvidia.com/nvidia
        chart: gpu-operator
        targetRevision: v25.3.0
      destination:
        server: '{{server}}' 
        namespace: nvidia-gpu
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      