apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tranarr
  namespace: argocd
  annotations:
    ai-agent-inventory-appname: "Transmission"
    appset-dashboard-appname: "Transmission torrent client"
    appset-dashboard-groupname: "Media"
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  tranarr: "installed"
                  csi-nfs: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{name}}-tranarr'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: tranarr
          values: |
            controllers:            
              main:
                type: deployment
                pod:
                  labels:
                    vpn: required                
                initContainers:
                  tranarr-restore-config:
                    image: 
                      repository: ghcr.io/vadimzharov/pdbackup
                      pullPolicy: IfNotPresent
                      tag: 0.0.8
                    args: 
                      - restore
                    envFrom:
                    - configMapRef:
                        name: tranarr-pdbackup-settings  
                    - secretRef:
                        name: tranarr-pdbackup-secret            
                containers:
                  main:
                    image: 
                      repository: ghcr.io/k8s-at-home/transmission
                      pullPolicy: IfNotPresent
                      tag: v3.00
                    env:
                      TRANSMISSION_DOWNLOAD_DIR: "/downloads/complete"
                      TRANSMISSION_INCOMPLETE_DIR: "/downloads/incomplete"
                      TRANSMISSION_INCOMPLETE_DIR_ENABLED: "true"
                      TRANSMISSION_WATCH_DIR: "/watch"
                      TRANSMISSION_WATCH_DIR_ENABLED: "false"
                      TRANSMISSION_WEB_HOME: "/web"
                      TZ: "CDT"                    
                  tranarr-backup-config-daemon:
                    image: 
                      repository: ghcr.io/vadimzharov/pdbackup
                      pullPolicy: IfNotPresent
                      tag: 0.0.8
                    args:
                      - daemon
                    envFrom:
                    - configMapRef:
                        name: tranarr-pdbackup-settings  
                    - secretRef:
                        name: tranarr-pdbackup-secret
            service:
              main:
                primary: true
                enabled: true
                controller: main
                ports:
                  http:
                    port: 9091
            ingress:
              main:
                enabled: false
                className: nginx
                hosts: 
                  - host: tranarr.{{ domainname }}
                    paths:
                      - path: /
                        pathType: Prefix
                        service:
                          name: tranarr
                          port: 9091
            route:
              main:
                enabled: true
                kind: HTTPRoute
                labels:
                  k8s-dashboard-group: Media
                  k8s-dashboard-appname: Transmission
                parentRefs:
                  - name: cilium-gw
                    namespace: cilium-system
                hostnames:
                  - tranarr.{{ domainname }}
                rules:  
                - matches:
                  - path:
                      type: PathPrefix
                      value: /
                  backendRefs:
                  - name: tranarr
                    port: 9091                          
            persistence:
              config:
                enabled: true
                type: emptyDir
                globalMounts:
                  - path: /config
                    readOnly: false
              downloads-incomplete:
                enabled: true
                type: emptyDir
                globalMounts:
                  - path: /downloads/incomplete
                    readOnly: false
              donwloads-complete:
                enabled: true
                type: persistentVolumeClaim
                existingClaim: tranarr-complete-pvc
                globalMounts:
                  - path: /downloads/complete
                    readOnly: false
              dedicated-movies:
                enabled: true
                type: persistentVolumeClaim
                existingClaim: tranarr-n-dedicated-movies-pvc
                globalMounts:
                  - path: /downloads/movies
                    readOnly: false                    
            configMaps:
              pdbackup-settings:
                enabled: true
                data:
                  PDBACKUP_S3_BUCKET: "backup-tranarr"
                  PDBACKUP_S3_PREFIX: "tranarr-pbbackup"
                  PDBACKUP_SOURCE_DIR: "/config"
                  PDBACKUP_TARGET_DIR: "/config"  
                  PDBACKUP_BACKUP_INTERVAL: "1h"
                  PDBACKUP_HOSTNAME: "tranarr"
                  PDBACKUP_RETENTION_KEEP_LATEST: "3"
                  PDBACKUP_FORCE_RESTORE: "true"
                  PDBACKUP_RESTORE_VERBOSE: "true"
              #b-r-settings:
              #  enabled: true
              #  data:
              #    AWS_BUCKET: "arr-bkp"
              #    S3_BUCKET_FOLDER: "tranarr-config"
              #    S3_FILE_PREFIX: "tranarr-config"
              #    BACKUP_INTERVAL: "1h"
              #    PRUNE_INTERVAL: "48h"
              #    COPIES_TO_KEEP: "15"
              #    FORCE_RESTORE: "true"
              #    DIR_TO_BACKUP: /config
              #    DIR_TO_RESTORE: /config
              #    ARCHIVE_TYPE: targz
            secrets:
              pdbackup-secret:
                enabled: true
                labels: {}
                annotations: {}
                stringData:
                  PDBACKUP_S3_ENDPOINT: "http://{{ minioendpoint }}"
                  PDBACKUP_S3_ACCESS_KEY: {{ miniokey }}
                  PDBACKUP_S3_SECRET_KEY: {{ miniosecretkey }}
                  PDBACKUP_KOPIA_PASSWORD: {{ encryptpassword }}            
              #b-r-creds:
              #  enabled: true
              #  labels: {}
              #  annotations: {}
              #  stringData:
              #    S3_ENDPOINT: {{ minioendpoint }}
              #    AWS_KEY: {{ miniokey }}
              #    AWS_SECRET_KEY: {{ miniosecretkey }}
            rawResources:
              complete-pv:
                apiVersion: v1
                kind: PersistentVolume
                spec:
                  spec:
                    capacity:
                      storage: 10Gi
                    accessModes:
                      - ReadWriteMany
                    persistentVolumeReclaimPolicy: Retain
                    storageClassName: sc-nfs-default
                    csi:
                      driver: nfs.csi.k8s.io
                      readOnly: false
                      # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
                      # make sure this value is unique for every share in the cluster
                      volumeHandle: "nfs-server#k8s-tranarr#k8s-tranarr-share"
                      volumeAttributes:
                        server: {{ k8s-nfs-server-name }}
                        share: {{ k8s-tranarr-share }}
              complete-pvc:
                apiVersion: v1
                kind: PersistentVolumeClaim
                spec:
                  spec:
                    storageClassName: sc-nfs-default
                    accessModes:
                      - ReadWriteMany
                    resources:
                      requests:
                        storage: 10Gi
                    volumeName: tranarr-complete-pv
              n-dedicated-movies-pv:
                apiVersion: v1
                kind: PersistentVolume
                spec:
                  spec:
                    capacity:
                      storage: 10Gi
                    accessModes:
                      - ReadWriteMany
                    persistentVolumeReclaimPolicy: Retain
                    storageClassName: sc-nfs-default
                    csi:
                      driver: nfs.csi.k8s.io
                      readOnly: false
                      # volumeHandle format: {nfs-server-address}#{sub-dir-name}#{share-name}
                      # make sure this value is unique for every share in the cluster
                      volumeHandle: "nfs-server#k8s-tranarr#k8s-tranarr-n-dedicated-share"
                      volumeAttributes:
                        server: {{ truenas-nfs-ip }}
                        share: "{{ truenas-arr-share }}/dedicated-movies"
              n-dedicated-movies-pvc:
                apiVersion: v1
                kind: PersistentVolumeClaim
                spec:
                  spec:
                    storageClassName: sc-nfs-default
                    accessModes:
                      - ReadWriteMany
                    resources:
                      requests:
                        storage: 10Gi
                    volumeName: tranarr-n-dedicated-movies-pv
        repoURL: https://bjw-s-labs.github.io/helm-charts
        chart: app-template
        targetRevision: 3.4.0
      destination:
        server: '{{server}}' 
        namespace: tranarr
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      
