apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: registry-mirrors
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "k8secrets/ingresses"
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  registry-mirrors: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{name}}-registry-mirrors'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: docker-mirror
          values: |
            controllers:
              docker:
                containers:
                  main:
                    image:
                      repository: docker.io/library/registry
                      pullPolicy: IfNotPresent
                      tag: 2
                    ports:
                    - name: http
                      containerPort: 5000
                      protocol: TCP
                    env:
                      REGISTRY_PROXY_REMOTEURL: "https://docker.io"
              k8s-registry:
                containers:
                  main:
                    image:
                      repository: docker.io/library/registry
                      pullPolicy: IfNotPresent
                      tag: 2
                    ports:
                    - name: http
                      containerPort: 5000
                      protocol: TCP
                    env:
                      REGISTRY_PROXY_REMOTEURL: "https://registry.k8s.io"
              quay:
                containers:
                  main:
                    image:
                      repository: docker.io/library/registry
                      pullPolicy: IfNotPresent
                      tag: 2
                    ports:
                    - name: http
                      containerPort: 5000
                      protocol: TCP
                    env:
                      REGISTRY_PROXY_REMOTEURL: "https://quay.io"
              gcr:
                containers:
                  main:
                    image:
                      repository: docker.io/library/registry
                      pullPolicy: IfNotPresent
                      tag: 2
                    ports:
                    - name: http
                      containerPort: 5000
                      protocol: TCP
                    env:
                      REGISTRY_PROXY_REMOTEURL: "https://gcr.io"
            service:
              docker:
                primary: true              
                enabled: true
                controller: docker
                ports:
                  http:
                    port: 5000
              k8s-registry:
                primary: false
                enabled: true
                controller: k8s-registry
                ports:
                  http:
                    port: 5000
              quay:
                primary: false
                enabled: true
                controller: quay
                ports:
                  http:
                    port: 5000
              gcr:
                primary: false
                enabled: true
                controller: quay
                ports:
                  http:
                    port: 5000                    
            ingress:
              docker:
                enabled: true
                className: '{{ metadata.labels.registry-mirrors-ingress }}'
                annotations:
                  nginx.ingress.kubernetes.io/service-upstream: "true"
                  nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
                  nginx.ingress.kubernetes.io/proxy-body-size: "0"
                hosts:
                  - host: docker-mirror.{{ domainname }}
                    paths:
                      - path: /
                        pathType: Prefix
                        service:
                          name: docker
                          port: 5000
              k8s-registry:
                enabled: true
                className: '{{ metadata.labels.registry-mirrors-ingress }}'
                annotations:
                  nginx.ingress.kubernetes.io/service-upstream: "true"
                  nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
                  nginx.ingress.kubernetes.io/proxy-body-size: "0"
                hosts:
                  - host: k8s-mirror.{{ domainname }}
                    paths:
                      - path: /
                        pathType: Prefix
                        service:
                          name: k8s-registry
                          port: 5000
              quay:
                enabled: true
                className: '{{ metadata.labels.registry-mirrors-ingress }}'
                annotations:
                  nginx.ingress.kubernetes.io/service-upstream: "true"
                  nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
                  nginx.ingress.kubernetes.io/proxy-body-size: "0"
                hosts:
                  - host: quay-mirror.{{ domainname }}
                    paths:
                      - path: /
                        pathType: Prefix
                        service:
                          name: quay
                          port: 5000
              gcr:
                enabled: true
                className: '{{ metadata.labels.registry-mirrors-ingress }}'
                annotations:
                  nginx.ingress.kubernetes.io/service-upstream: "true"
                  nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
                  nginx.ingress.kubernetes.io/proxy-body-size: "0"
                hosts:
                  - host: gcr-mirror.{{ domainname }}
                    paths:
                      - path: /
                        pathType: Prefix
                        service:
                          name: gcr
                          port: 5000
        repoURL: https://bjw-s-labs.github.io/helm-charts
        chart: app-template
        targetRevision: 3.4.0        
      destination:
        server: '{{server}}' 
        namespace: registry-mirrors
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      