apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloudnative-pg
  namespace: argocd  
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  cloudnative-pg: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{name}}-cloudnative-pg'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: cloudnative-pg
        repoURL: https://cloudnative-pg.github.io/charts
        chart: cloudnative-pg
        targetRevision: 0.26.1
      - repoURL: https://github.com/cloudnative-pg/plugin-barman-cloud.git
        targetRevision: 'v0.9.0'
        path: kubernetes/
      - helm:
          releaseName: backup-config
          values: |
            controllers: 
              main:
               enabled: false
            rawResources:
              barmanobjectstore:
                apiVersion: barmancloud.cnpg.io/v1
                kind: ObjectStore
                spec:
                  spec:
                    configuration:
                      destinationPath: s3://cloudnative-pg-backups/
                      endpointURL: http://{{ minioendpoint }}
                      s3Credentials:
                        accessKeyId:
                          name: minio
                          key: {{ miniokey }}
                        secretAccessKey:
                          name: minio
                          key: {{ miniosecretkey }}
                      wal:
                        compression: gzip
        repoURL: https://bjw-s-labs.github.io/helm-charts
        chart: app-template
        targetRevision: 4.4.0        
      destination:
        server: '{{server}}' 
        namespace: cnpg-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
      