apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ollama
  namespace: argocd
  annotations:
    appset-dashboard-appname: "Ollama"
    appset-dashboard-groupname: "AI tools"
    k8s-dashboard-group: "AI tools"
    k8s-dashboard-appname: "Ollama"
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  ollama: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{name}}-ollama'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: ollama
          values: |
            ollama:
              gpu:
                enabled: false
              models:
                pull:
                  - llama3.2:1b
                  - qwen2.5:1.5b
                run:
                  - llama3.2:1b
                  - qwen2.5:1.5b
            httpRoute:
              enabled: true
              hostnames:
                - ollama.{{ domainname }}
              parentRefs:
                - name: cilium-gw
                  namespace: cilium-system
            resources:
              requests:
                memory: 2Gi
                cpu: 500m
              limits:
                memory: 4Gi
                cpu: 2000m
        repoURL: https://otwld.github.io/ollama-helm/
        chart: ollama
        targetRevision: 1.70.0
      destination:
        server: '{{server}}' 
        namespace: ollama
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      