apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vpn-switcher
  namespace: argocd
  annotations:
    appset-dashboard-appname: "VPN switcher"
    appset-dashboard-groupname: "K8S tools"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  vpn-switcher: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{ .name }}-vpnswitcher'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: vpnswitcher
          values: |
            image:
              repository: ghcr.io/vadimzharov/vpn-switcher
              pullPolicy: IfNotPresent
              tag: latest
            httpRoute:
              hostname: vpn.{{ .domainname }}
              gatewayName: cilium-gw
              gatewayNamespace: cilium-system
              annotations:
                k8s-dashboard-group: Tools
                k8s-dashboard-appname: VPN switcher
                k8s-dashboard-searchname: VPN
            config:
            {{ .vpnswitcherconfig | indent 14 }}
        repoURL: oci://ghcr.io/vadimzharov/charts/vpn-switcher
        targetRevision: 0.1.0
        path: .
      destination:
        server: '{{ .server }}'
        namespace: vpn-switcher
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true          