apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: viewtube
  namespace: argocd
  annotations:
    ai-agent-inventory-appname: "ViewTube"
    appset-dashboard-appname: "ViewTube (youtube self-hosted)"
    appset-dashboard-groupname: "Media"
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  viewtube: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{name}}-viewtube'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: viewtube
          values: |      
            service:           
              main:
                controller: main
                enabled: true
                ports:
                  http:
                    port: 8066
              redis:
                enabled: true
                controller: redis
                ports:
                  http:
                    port: 6379
              mongodb:
                controller: mongodb
                enabled: true
                ports:
                  http:
                    port: 27017
            ingress:
              main:
                enabled: true
                className: nginx
                hosts:
                  - host: viewtube.{{ domainname }}
                    paths:
                      - path: /
                        pathType: Prefix
                        service:
                          identifier: main
            persistence:
              viewtube-data:
                enabled: true
                type: emptyDir
                advancedMounts:
                  main:
                    main:
                      - path: /data
              redis-data:
                enabled: true
                type: emptyDir
                advancedMounts:
                  redis:
                    main:
                      - path: /data
              mongodb-data:
                enabled: true
                type: emptyDir
                advancedMounts:
                  mongodb:
                    main:
                      - path: /data/db
            controllers:
              main:
                enabled: true
                type: deployment
                replicas: 1
                pod:
                  labels:
                    vpn: required
                containers:
                  main:
                    image:
                      repository: mauriceo/viewtube
                      pullPolicy: IfNotPresent
                      tag: latest
                    env:
                      VIEWTUBE_DATABASE_HOST: viewtube-mongodb
                      VIEWTUBE_REDIS_HOST: viewtube-redis
              redis:
                enabled: true
                type: deployment
                replicas: 1
                containers:
                  main:
                    image:
                      repository: redis
                      pullPolicy: IfNotPresent
                      tag: 7
              mongodb:
                enabled: true
                type: deployment
                replicas: 1
                containers:
                  main:
                    image:
                      repository: mongo
                      pullPolicy: IfNotPresent
                      tag: 7                      
        repoURL: https://bjw-s-labs.github.io/helm-charts
        chart: app-template
        targetRevision: 3.4.0
      destination:
        server: '{{server}}' 
        namespace: viewtube
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      