apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vpn-switcher
  namespace: argocd
  annotations:
    appset-dashboard-appname: "VPN switcher"
    appset-dashboard-groupname: "K8S tools"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  vpn-switcher: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{ .name }}-vpnswitcher'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: vpnswitcher
          values: |
            controllers: 
              main:
               enabled: false
            rawResources:
              vpnswitcher-config:
                apiVersion: v1
                kind: Secret
                nameOverride: config
                spec:
                  data:
                    config.yaml: {{ .vpnswitcherconfig | b64enc }}
        repoURL: https://bjw-s-labs.github.io/helm-charts
        chart: app-template
        targetRevision: 3.4.0
      - helm:
          releaseName: vpnswitcher-app
          values: |
            controllers:            
              main:
                type: deployment             
                containers:
                  main:
                    image: 
                      repository: quay.io/vadimzharov/vpnswitcher
                      pullPolicy: IfNotPresent
                      tag: latest
            service:
              main:
                primary: true
                enabled: true
                controller: main
                ports:
                  http:
                    port: 8080
            route:
              main:
                enabled: true
                kind: HTTPRoute
                labels:
                  k8s-dashboard-group: Tools
                  k8s-dashboard-appname: VPN-switcher
                parentRefs:
                  - name: cilium-gw
                    namespace: cilium-system
                hostnames:
                  - vpn.{{ .domainname }}
                rules:  
                - matches:
                  - path:
                      type: PathPrefix
                      value: /
                  backendRefs:
                  - name: vpnswitcher-app
                    port: 8080
            persistence:
              vpnswitcher-config:
                enabled: true
                type: secret
                name: vpnswitcher-config
                globalMounts:
                  - path: /etc/vpnswitcher/config.yaml
                    subPath: config.yaml
        repoURL: https://bjw-s-labs.github.io/helm-charts
        chart: app-template
        targetRevision: 3.4.0                
      destination:
        server: '{{ .server }}'
        namespace: vpn-switcher
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true          