apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cilium-v2-config
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  cilium-v2-config: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "{{ name }}-cni-secrets"
  template:
    metadata:
      name: '{{ name }}-cilium-v2-config' 
    spec:
      project: k8s-homelab-cluster
      sources:
      - helm:
          releaseName: cilium-config
          values: |
            controllers: 
              main:
               enabled: false
            rawResources:
              bgpclusterconfig:
                apiVersion: cilium.io/v2
                kind: CiliumBGPClusterConfig
                spec:
                  spec:
                    nodeSelector:
                      matchLabels:
                        node-role.kubernetes.io/bgp-router: enabled
                    bgpInstances:
                    - name: "mikrotik-instance"
                      localASN: {{ cilium_bgp_local_asn }}
                      localPort: 179
                      peers:
                      - name: "peer-to-router"
                        peerASN: {{ router_bgp_peer_asn }}
                        peerAddress: {{ router_bgp_peer_ip }}
                        peerConfigRef:
                          name: "cilium-config-bgppeerconfig"
              bgppeerconfig:
                apiVersion: cilium.io/v2
                kind: CiliumBGPPeerConfig
                spec:
                  spec:
                    timers:
                      holdTimeSeconds: 9
                      keepAliveTimeSeconds: 3
                    gracefulRestart:
                      enabled: true
                      restartTimeSeconds: 15
                    families:
                      - afi: ipv4
                        safi: unicast
                        advertisements:
                          matchLabels:
                            advertise: "bgp"              
              bgpadvertisement:
                apiVersion: cilium.io/v2
                kind: CiliumBGPAdvertisement
                labels:
                  advertise: bgp
                spec:
                  spec:
                    advertisements:
                      - advertisementType: "Service"
                        service:
                          addresses:
                            - LoadBalancerIP
                        selector:
                          matchExpressions:
                          - {key: somekey, operator: NotIn, values: ['never-used-value']}               
              loadbalancerpool:
                apiVersion: "cilium.io/v2"
                kind: CiliumLoadBalancerIPPool
                spec:
                  spec:
                    blocks:
                    - cidr: {{ load-balancer-cidr }}
                    allowFirstLastIPs: "No"
              egresspolicy:
                apiVersion: cilium.io/v2
                kind: CiliumEgressGatewayPolicy
                spec:
                  spec:
                    selectors:
                    - podSelector:
                        matchLabels:
                          vpn: required
                    destinationCIDRs:
                      - 0.0.0.0/0
                    egressGateway:
                      egressIP: {{ egressipvpn }}
                      nodeSelector:
                        matchLabels:
                          node-role.kubernetes.io/egress-gw: vpn
              gatewayclass:
                apiVersion: gateway.networking.k8s.io/v1beta1
                kind: GatewayClass
                forceRename: "cilium-lb"
                spec:
                  spec:
                    controllerName: io.cilium/gateway-controller
                    description: The LoadBalancer type Cilium GatewayClass
                    parametersRef:
                      group: cilium.io
                      kind: CiliumGatewayClassConfig
                      name: lb-gateway-config
                      namespace: cilium-system
              ciliumgatewayclassconfig:
                apiVersion: cilium.io/v2alpha1
                kind: CiliumGatewayClassConfig
                forceRename: lb-gateway-config
                spec:
                  spec:
                    service:
                      type: LoadBalancer

        repoURL: https://bjw-s-labs.github.io/helm-charts
        chart: app-template
        targetRevision: 4.4.0
      destination:
        server: '{{server}}'
        namespace: cilium-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          