apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  metrics-server: "installed"
  template:
    metadata:
      name: '{{ name }}-metrics-server' 
    spec:
      project: k8s-homelab-cluster
      sources:
      - helm:
          releaseName: metrics-server
        repoURL: https://kubernetes-sigs.github.io/metrics-server/
        chart: metrics-server
        targetRevision: 3.12.1
      destination:
        server: '{{server}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          