apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-certificates-sync
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  nginx-certs-sync: "installed"
                  nginx: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "wildcard-apps-certificate"
                  namespaceName: "ingress-nginx"
  template:
    metadata:
      name: '{{ .name }}-nginx-certs'
    spec:
      project: k8s-homelab-cluster
      sources:
      - helm:
          releaseName: wildcard
          values: |
            controllers: 
              main:
               enabled: false
            rawResources:
              wildcard-certs:
                apiVersion: v1
                kind: Secret
                nameOverride: apps-certificate
                spec:
                  data:
                    tls.crt: {{ .tls_crt | b64enc }}
                    tls.key: {{ .tls_key | b64enc }}
        repoURL: https://bjw-s.github.io/helm-charts
        chart: app-template
        targetRevision: 3.4.0
      destination:
        server: '{{ .server }}'
        namespace: ingress-nginx
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

          