apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cilium-gw
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  cilium-gw: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "{{ name }}-cni-secrets"
  template:
    metadata:
      name: '{{ name }}-cilium-gw' 
    spec:
      project: k8s-homelab-cluster
      sources:
      - helm:
          releaseName: cilium-gw
          values: |
            debug:
              enabled: false
            securityContext:
              privileged: true              
            bgpControlPlane:
              enabled: true
            operator:
              replicas: 1
            prometheus:
              enabled: true
            bpf:
              masquerade: true
            tls:
              ca:
                cert: {{ cilium-ca }}
                key: {{ cilium-ca-key }}     
            cluster:
              id: {{ cilium-clusterid }}
              name: {{ cilium-clustername }}
            clustermesh:
              apiserver:
                service:
                  type: NodePort
                  nodePort: {{ mesh-api-port }}
                nodeSelector:
                  node-role.kubernetes.io/control-plane: ""
                tls:
                  authMode: cluster
                  server:
                    extraDnsNames:
                      - "*.{{ mesh-domain }}"
                      - "*.k8s03.{{ mesh-domain }}"
                      - "*.k8s03.{{ mesh-domain }}"
                      - "*.k8s04.{{ mesh-domain }}"
              config:
                enabled: false
                domain: "{{ mesh-domain }}"
                clusters:
                  - name: {{ mesh-peer-cluster1name }}
                    address: {{ mesh-peer-cluster1address }}
                    port:  {{ mesh-peer-cluster1port }}
                  #- name: {{ mesh-peer-cluster2name }}
                  #  address: {{ mesh-peer-cluster2address }}
                  #  port:  {{ mesh-peer-cluster2port }}                    
              useAPIServer: true
            ipv4:
              enabled: true
            nodePort:
              enabled: true
            egressGateway:
              enabled: true
            gatewayAPI:
              enabled: true
            ipam:
              mode: "cluster-pool"
              operator:
                clusterPoolIPv4PodCIDRList: 
                  - {{ cilium-podcidr }}
                clusterPoolIPv4MaskSize: 24
            l7Proxy: true  
            kubeProxyReplacement: true
            k8sServiceHost: {{ k8s-servicehost }}
            k8sServicePort: 6443          
            cgroup:
              autoMount:
                enabled: false
              hostRoot: /sys/fs/cgroup                    
            externalWorkloads:
              enabled: true
            hubble:
              metrics:
                enabled: 
                - dns:query;ignoreAAAA
                - drop
                - tcp
                - flow
                - icmp
                - http            
              relay: 
                enabled: true
              ui:
                enabled: true
              tls:
                auto:
                  enabled: true 
                  method: helm  
                  certValidityDuration: 1095
        repoURL: https://helm.cilium.io/
        chart: cilium
        targetRevision: '{{metadata.labels.cilium-version}}'
      - repoURL: https://github.com/kubernetes-sigs/gateway-api.git
        targetRevision: 'v1.2.0'
        path: config/crd/standard
      - repoURL: https://github.com/kubernetes-sigs/gateway-api.git
        targetRevision: 'v1.2.0'
        path: config/crd/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
      destination:
        server: '{{server}}'
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          