apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-clusters-photoprism-secrets
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: photoprism-app-secrets
    creationPolicy: Owner
  data:
  - secretKey: domainname
    remoteRef:
      key: apps/configs
      property: domainname
  - secretKey: minioendpoint
    remoteRef:
      key: apps/backup
      property: minioendpoint
  - secretKey: miniokey
    remoteRef:
      key: apps/backup
      property: miniokey
  - secretKey: miniosecretkey
    remoteRef:
      key: apps/backup
      property: miniosecretkey
  - secretKey: PHOTOPRISM_ADMIN_PASSWORD
    remoteRef:
      key: apps/photoprism
      property: PHOTOPRISM_ADMIN_PASSWORD
  - secretKey: PHOTOPRISM_ADMIN_USER
    remoteRef:
      key: apps/photoprism
      property: PHOTOPRISM_ADMIN_USER
  - secretKey: MARIADB_DATABASE
    remoteRef:
      key: apps/photoprism
      property: MARIADB_DATABASE
  - secretKey: MARIADB_USER
    remoteRef:
      key: apps/photoprism
      property: MARIADB_USER
  - secretKey: MARIADB_PASSWORD
    remoteRef:
      key: apps/photoprism
      property: MARIADB_PASSWORD
  - secretKey: MARIADB_ROOT_PASSWORD
    remoteRef:
      key: apps/photoprism
      property: MARIADB_ROOT_PASSWORD
  - secretKey: k8s-photoprism-originals-share
    remoteRef:
      key: apps/photoprism
      property: k8s-photoprism-originals-share
  - secretKey: k8s-photoprism-storage-share
    remoteRef:
      key: apps/photoprism
      property: k8s-photoprism-storage-share
  - secretKey: k8s-nfs-server-name
    remoteRef:
      key: infra/nfs
      property: k8s-nfs-server-name


