apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-clusters-immich-secrets
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: immich-app-secrets
    creationPolicy: Owner
  data:
  - secretKey: pgsql_username
    remoteRef:
      key: apps/immich
      property: pgsql_username
  - secretKey: pgsql_password
    remoteRef:
      key: apps/immich
      property: pgsql_password
  - secretKey: pgsql_database
    remoteRef:
      key: apps/immich
      property: pgsql_database 
  - secretKey: domainname
    remoteRef:
      key: apps/configs
      property: domainname
  - secretKey: minioendpoint
    remoteRef:
      key: apps/backup
      property: minioendpoint
  - secretKey: miniokey
    remoteRef:
      key: apps/backup
      property: miniokey
  - secretKey: miniosecretkey
    remoteRef:
      key: apps/backup
      property: miniosecretkey

