apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-clusters-infra-secrets
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: k8s-clusters-infra-secrets
    creationPolicy: Owner
  dataFrom:
    - extract: 
        key: infra-secrets    
  data:
  - secretKey: k8s-nfs-server-name
    remoteRef:
      key: infra/nfs
      property: k8s-nfs-server-name
  - secretKey: k8s-nfs-share-name
    remoteRef:
      key: infra/nfs
      property: k8s-nfs-share-name
  - secretKey: synasip
    remoteRef:
      key: infra/iscsi
      property: synasip
  - secretKey: synasuser
    remoteRef:
      key: infra/iscsi
      property: synasuser
  - secretKey: synaspassword
    remoteRef:
      key: infra/iscsi
      property: synaspassword
  - secretKey: cloudflareapitoken
    remoteRef:
      key: certs/issuer
      property: cloudflareapitoken
  - secretKey: dnszones
    remoteRef:
      key: certs/issuer
      property: dnszones
  - secretKey: email
    remoteRef:
      key: certs/issuer
      property: email
  - secretKey: letsencryptpk
    remoteRef:
      key: certs/issuer
      property: letsencryptpk
  - secretKey: wildcarddnsname
    remoteRef:
      key: certs/ingress-wildcard-certificate
      property: wildcard-dns-name
  - secretKey: truenas-api-key
    remoteRef:
      key: infra/truenas
      property: truenas-api-key
  - secretKey: truenas-ip
    remoteRef:
      key: infra/truenas
      property: truenas-ip
  - secretKey: truenas-networks
    remoteRef:
      key: infra/truenas
      property: truenas-networks
  - secretKey: truenas-tginitiatorgroup
    remoteRef:
      key: infra/truenas
      property: truenas-tginitiatorgroup
  - secretKey: minioendpoint
    remoteRef:
      key: apps/backup
      property: minioendpoint
  - secretKey: miniokey
    remoteRef:
      key: apps/backup
      property: miniokey
  - secretKey: miniosecretkey
    remoteRef:
      key: apps/backup
      property: miniosecretkey
  - secretKey: domainname
    remoteRef:
      key: apps/configs
      property: domainname      