apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s-clusters-apps-secrets
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: k8s-clusters-apps-secrets
    creationPolicy: Owner
  data:
  - secretKey: vpnswitcherconfig
    remoteRef:
      key: apps/configs
      property: vpnswitcherconfig
  - secretKey: domainname
    remoteRef:
      key: apps/configs
      property: domainname
  - secretKey: minioendpoint
    remoteRef:
      key: apps/backup
      property: minioendpoint
  - secretKey: miniokey
    remoteRef:
      key: apps/backup
      property: miniokey
  - secretKey: miniosecretkey
    remoteRef:
      key: apps/backup
      property: miniosecretkey
  - secretKey: password
    remoteRef:
      key: apps/configs
      property: password
  - secretKey: invidioushmackey
    remoteRef:
      key: apps/configs
      property: invidioushmackey
  - secretKey: invidiouspgpw
    remoteRef:
      key: apps/configs
      property: invidiouspgpw
  - secretKey: k8s-nfs-server-name
    remoteRef:
      key: infra/nfs
      property: k8s-nfs-server-name
  - secretKey: k8s-nfs-share-name
    remoteRef:
      key: infra/nfs
      property: k8s-nfs-share-name
  - secretKey: k8s-tranarr-dedicated-share
    remoteRef:
      key: apps/arr
      property: k8s-tranarr-dedicated-share
  - secretKey: k8s-tranarr-share
    remoteRef:
      key: apps/arr
      property: k8s-tranarr-share
  - secretKey: k8s-sonarr-share
    remoteRef:
      key: apps/arr
      property: k8s-sonarr-share
  - secretKey: k8s-radarr-share
    remoteRef:
      key: apps/arr
      property: k8s-radarr-share
  - secretKey: awsbucket
    remoteRef:
      key: apps/backup
      property: awsbucket
  - secretKey: awskey
    remoteRef:
      key: apps/backup
      property: awskey
  - secretKey: awssecretkey
    remoteRef:
      key: apps/backup
      property: awssecretkey
  - secretKey: encryptpassword
    remoteRef:
      key: apps/backup
      property: encryptpassword
  - secretKey: vwadminkey
    remoteRef:
      key: apps/vaultwarden
      property: vwadminkey      




