apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s03-cni-secrets
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: k8s03-cni-secrets
    creationPolicy: Owner
  data:
  - secretKey: cilium-ca
    remoteRef:
      key: clusters/cilium
      property: cilium-ca
  - secretKey: cilium-ca-key
    remoteRef:
      key: clusters/cilium
      property: cilium-ca-key
  - secretKey: mesh-domain
    remoteRef:
      key: clusters/cilium
      property: mesh-domain  
  - secretKey: cilium-clusterid
    remoteRef:
      key: clusters/k8s03/cilium
      property: cilium-clusterid
  - secretKey: cilium-clustername
    remoteRef:
      key: clusters/k8s03/cilium
      property: cilium-clustername
  - secretKey: cilium-podcidr
    remoteRef:
      key: clusters/k8s03/cilium
      property: cilium-podcidr
  - secretKey: k8s-servicehost
    remoteRef:
      key: clusters/k8s03/cilium
      property: k8s-servicehost
  - secretKey: mesh-api-port
    remoteRef:
      key: clusters/k8s03/cilium
      property: mesh-api-port
  - secretKey: mesh-peer-cluster1address
    remoteRef:
      key: clusters/k8s03/cilium
      property: mesh-peer-cluster1address
  - secretKey: mesh-peer-cluster1name
    remoteRef:
      key: clusters/k8s03/cilium
      property: mesh-peer-cluster1name
  - secretKey: mesh-peer-cluster1port
    remoteRef:
      key: clusters/k8s03/cilium
      property: mesh-peer-cluster1port
  - secretKey: mesh-peer-cluster2address
    remoteRef:
      key: clusters/k8s03/cilium
      property: mesh-peer-cluster2address
  - secretKey: mesh-peer-cluster2name
    remoteRef:
      key: clusters/k8s03/cilium
      property: mesh-peer-cluster2name
  - secretKey: mesh-peer-cluster2port
    remoteRef:
      key: clusters/k8s03/cilium
      property: mesh-peer-cluster2port
  - secretKey: load-balancer-cidr
    remoteRef:
      key: clusters/k8s03/cilium
      property: load-balancer-cidr
  - secretKey: cilium_bgp_local_asn
    remoteRef:
      key: clusters/cilium
      property: cilium_bgp_local_asn
  - secretKey: router_bgp_peer_ip
    remoteRef:
      key: clusters/cilium
      property: router_bgp_peer_ip
  - secretKey: router_bgp_peer_asn
    remoteRef:
      key: clusters/cilium
      property: router_bgp_peer_asn
  - secretKey: egressipvpn
    remoteRef:
      key: clusters/k8s03/cilium
      property: egressipvpn


