apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s01-pihole-secrets
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: k8s01-pihole-secrets
    creationPolicy: Owner
  data:
  - secretKey: domainname
    remoteRef:
      key: apps/configs
      property: domainname
  - secretKey: piholelpip
    remoteRef:
      key: clusters/k8s01/pihole
      property: piholelpip
  - secretKey: piholeupstreamdns
    remoteRef:
      key: apps/pihole
      property: piholeupstreamdns
  - secretKey: piholepassword
    remoteRef:
      key: apps/pihole
      property: piholepassword
  - secretKey: blacklist
    remoteRef:
      key: apps/pihole
      property: blacklist
  - secretKey: whitelist
    remoteRef:
      key: apps/pihole
      property: whitelist
