apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k8s02-cni-secrets
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: k8s02-cni-secrets
    creationPolicy: Owner
  data:
  - secretKey: cilium-ca
    remoteRef:
      key: clusters/cilium
      property: cilium-ca
  - secretKey: cilium-ca-key
    remoteRef:
      key: clusters/cilium
      property: cilium-ca-key
  - secretKey: mesh-domain
    remoteRef:
      key: clusters/cilium
      property: mesh-domain