apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: opencode
  namespace: argocd
  annotations:
    appset-dashboard-appname: "OpenCode"
    appset-dashboard-groupname: "AI tools"
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  opencode: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{name}}-opencode'
    spec:
      project: k8s-homelab-apps
      sources:
      - helm:
          releaseName: opencode
          values: |
            image:
              tag: "0.2.0"
            serverPassword: "{{ password }}"
            buildkit:
              enabled: true
            rawResources:
              - apiVersion: v1
                kind: Secret
                metadata:
                  name: opencode-env
                  namespace: opencode
                type: Opaque
                stringData:
                  GH_TOKEN: "{{ opencode-gh-token }}"
                  LITELLM_API_KEY: "{{ opencode-litellm-api-key }}"
              - apiVersion: v1
                kind: Secret
                metadata:
                  name: opencode-ssh
                  namespace: opencode
                type: Opaque
                data:
                  id_ed25519: "{{ opencode-ssh-privatekey }}"
                  id_ed25519.pub: "{{ opencode-ssh-publickey }}"
                  known_hosts: "{{ github-known-hosts }}"
            envSecretName: opencode-env
            sshSecretName: opencode-ssh
            httpRoute:
              enabled: true
              host: "opencode.{{ domainname }}"
              parentRefs:
                - name: cilium-gw
                  namespace: cilium-system
                  sectionName: https-gw
              annotations:
                k8s-dashboard-group: AI tools
                k8s-dashboard-appname: OpenCode
        repoURL: oci://ghcr.io/vadimzharov/opencode-container/charts/opencode
        targetRevision: 0.2.0
        path: .
      destination:
        server: '{{server}}'
        namespace: opencode
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
