apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-external
  namespace: argocd
  annotations:
    appset-dashboard-appname: "Nginx External"
    appset-dashboard-groupname: "K8S Ingress controllers"    
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  nginx-external: "installed"
          - plugin:
              # Specify the configMap where the plugin configuration is located.
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "{{ name }}-network-secrets"
  template:
    metadata:
      name: '{{name}}-nginx-external'
    spec:
      project: k8s-homelab-cluster
      sources:
      - helm:
          releaseName: nginx-external
          values: |
            controller:
              extraArgs:
                default-ssl-certificate: "ingress-nginx/wildcard-apps-certificate"
              service:
                enabled: true
                loadBalancerIP: {{ nginxexternalingressip }}
              ingressClassResource:
                name: nginx-external
                default: false
                controllerValue: "k8s.io/ingress-nginx-external"
              ingressClass: nginx-external
            tcp:
              5000: "ingress-nginx-external/nginx-external-ingress-nginx-controller:443"
              6443: "ingress-nginx-external/nginx-external-ingress-nginx-controller:443"
        repoURL: https://kubernetes.github.io/ingress-nginx
        chart: ingress-nginx
        targetRevision: 4.12.1
      destination:
        server: '{{server}}'
        namespace: ingress-nginx-external
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          
