apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: uptime-kuma
  namespace: argocd
  annotations:
    appset-dashboard-appname: "Uptime Kuma"
    appset-dashboard-groupname: "K8S monitoring tools"    
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  uptime-kuma: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{name}}-uptime-kuma'
    spec:
      project: k8s-homelab-infra
      sources:      
      - helm:
          releaseName: 'uptime-kuma-{{ name }}'
          values: |
            persistence:
              enabled: true
            readinessProbe:
              httpGet:
                path: /
                port: http
                scheme: HTTP
              timeoutSeconds: 1
              periodSeconds: 180
              successThreshold: 1
              failureThreshold: 3              
            livenessProbe:
              exec:
                command:
                  - extra/healthcheck                
              timeoutSeconds: 1
              periodSeconds: 180
              successThreshold: 1
              failureThreshold: 3                  
            ingress:
              enabled: true
              className: nginx
              annotations:
                nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              labels:
                k8s-dashboard-group: Tools                     
              hosts:
                - host: uptime-kuma.{{ domainname }}
                  paths:
                    - path: /
                      pathType: ImplementationSpecific              
        repoURL: https://k3rnelpan1c-dev.github.io/uptime-kuma-helm/
        chart: uptime-kuma
        targetRevision: 1.5.0
      destination:
        server: '{{server}}' 
        namespace: uptime-kuma
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      