apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-external-certs
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  nginx-external-certs: "installed"
          - plugin:
              # Specify the configMap where the plugin configuration is located.
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "wildcard-apps-certificate"
                  namespaceName: "ingress-nginx"
  template:
    metadata:
      name: '{{.name}}-nginx-external-certs'
    spec:
      project: k8s-homelab-cluster
      sources:
      - helm:
          releaseName: nginx-certs
          values: |
            controllers: 
              main:
               enabled: false
            rawResources:
              wildcard-certs:
                apiVersion: v1
                kind: Secret
                nameOverride: apps-certificate
                spec:
                  data:
                    tls.crt: {{ .tls_crt | b64enc }}
                    tls.key: {{ .tls_key | b64enc }}             
        repoURL: https://bjw-s.github.io/helm-charts
        chart: app-template
        targetRevision: 3.4.0
      destination:
        server: '{{.server}}'
        namespace: ingress-nginx-external
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          