apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  cert-manager: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-infra-secrets" 
  template:
    metadata:
      name: '{{ .name }}-cert-manager' 
    spec:
      project: k8s-homelab-infra
      sources:
      - helm:
          values: |
            installCRD: true
            extraArgs:
              - --dns01-recursive-nameservers-only
              - --dns01-recursive-nameservers=jen.ns.cloudflare.com:53,venkat.ns.cloudflare.com:53
          parameters:
            - name: installCRDs
              value: "true"
        repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: v1.12.0
      - helm:
          releaseName: cm-config
          values: |
            controllers: 
              main:
               enabled: false
            rawResources:
              cloudflare-api-token:
                apiVersion: v1
                kind: Secret
                spec:
                  data:
                    api-token: {{ .cloudflareapitoken | b64enc }}
              clusterissuer:
                apiVersion: cert-manager.io/v1
                kind: ClusterIssuer
                spec:
                  spec:
                    acme:
                      email: {{ .email }}
                      preferredChain: ''
                      privateKeySecretRef:
                        name:  letsencrypt-prod
                      server: https://acme-v02.api.letsencrypt.org/directory
                      solvers:
                        - dns01:
                            cloudflare:
                              apiTokenSecretRef:
                                key: api-token
                                name: cm-config-cloudflare-api-token
                              email: {{ .email }}
                          selector:
                            dnsZones:
                              - {{ .dnszones }}
        repoURL: https://bjw-s.github.io/helm-charts
        chart: app-template
        targetRevision: 3.4.0        
      destination:
        server: '{{ .server }}'
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          