apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-manager
  namespace: argocd
  annotations:
    appset-dashboard-appname: "ArgoCD ApplicationSet Manager"
    appset-dashboard-groupname: "K8S tools"
spec:
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  appset-manager: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-apps-secrets"
  template:
    metadata:
      name: '{{name}}-appset-manager'
    spec:
      project: k8s-homelab-infra
      sources:
        - helm:
            releaseName: appset-manager
            values: |
              argocdNamespace: argocd
              ingress:
                enabled: true
                className: nginx
                host: appsets.{{ domainname }}
              config:
                auth:
                  username: admin
                  password: "{{ password }}"
          repoURL: oci://ghcr.io/vadimzharov/charts/appset-manager
          targetRevision: 0.0.4
          path: .
      destination:
        server: '{{server}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
