apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: democratic-csi
  namespace: argocd
  annotations:
    appset-dashboard-appname: "Democratic CSI"
    appset-dashboard-groupname: "K8S Storage"
  labels:
    appset-dashboard-locked: "true"          
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  democratic-csi: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "k8s-clusters-infra-secrets"
  template:
    metadata:
      name: '{{name}}-democratic-csi' 
    spec:
      project: k8s-homelab-infra
      sources:
      - helm:
          releaseName: democtratic-csi
          values: |
            csiDriver:
              name: "org.democratic-csi.iscsi"
            storageClasses:
              - name: freenas-iscsi-csi
                defaultClass: false
                reclaimPolicy: Delete
                volumeBindingMode: Immediate
                allowVolumeExpansion: true
                parameters:
                  fsType: ext4
                mountOptions: []
            driver:
              config:
                driver: freenas-api-iscsi
                instance_id:
                httpConnection:
                  protocol: https
                  host: "{{truenas-ip}}"
                  port: 443
                  apiKey: "{{truenas-api-key}}"
                  username: truenas_admin
                  allowInsecure: true
                  apiVersion: 2           
                zfs:
                  datasetParentName: main-pool/{{name}}
                  detachedSnapshotsDatasetParentName: main-pool/{{name}}-snaps
                  datasetEnableQuotas: true
                  datasetEnableReservation: false
                  datasetPermissionsMode: "0770"
                  datasetPermissionsUser: 0
                  datasetPermissionsGroup: 0
                iscsi:
                  targetPortal: "{{truenas-ip}}:3260"
                  interface:
                  namePrefix: csi-
                  nameSuffix: "-{{name}}"
                  targetGroups:
                    - targetGroupPortalGroup: 1
                      targetGroupInitiatorGroup: {{truenas-tginitiatorgroup}}
                      targetGroupAuthType: None  

        repoURL: https://democratic-csi.github.io/charts/
        chart: democratic-csi
        targetRevision: 0.15.1
      destination:
        server: '{{server}}'
        namespace: democratic-csi
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          