apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cilium-external-gw
  namespace: argocd
  annotations:
    appset-dashboard-appname: "Cilium external gateway configuration"
    appset-dashboard-groupname: "K8S Ingress controllers"
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  cilium-external-gw: "installed"
          - plugin:
              configMapRef:
                name: argocd-secrets-plugin
              input:
                parameters:
                  secretName: "{{ name }}-network-secrets"
  template:
    metadata:
      name: '{{ name }}-cilium-external-gw' 
    spec:
      project: k8s-homelab-cluster
      sources:
      - helm:
          releaseName: cilium-external-gw
          values: |
            controllers: 
              main:
               enabled: false
            rawResources:
              gateway:
                apiVersion: gateway.networking.k8s.io/v1
                kind: Gateway
                forceRename: cilium-external-gw
                spec:
                  spec:
                    gatewayClassName: cilium-lb
                    infrastructure:
                      annotations:
                        io.cilium/lb-ipam-ips: "{{ nginxexternalingressip }}"
                    listeners:
                    - protocol: HTTP
                      port: 80
                      name: web-gw
                      allowedRoutes:
                        namespaces:
                          from: All
                    - protocol: HTTPS
                      port: 443
                      tls:
                        mode: Terminate
                        certificateRefs:
                          - kind: Secret
                            name: wildcard-apps-certificate
                      name: https-gw
                      allowedRoutes:
                        namespaces:
                          from: All
                    - protocol: HTTPS
                      port: 5000
                      tls:
                        mode: Terminate
                        certificateRefs:
                          - kind: Secret
                            name: wildcard-apps-certificate
                      name: https-gw-5k
                      allowedRoutes:
                        namespaces:
                          from: All                          
        repoURL: https://bjw-s-labs.github.io/helm-charts
        chart: app-template
        targetRevision: 4.4.0
      destination:
        server: '{{server}}'
        namespace: cilium-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          